import type { ExecutionCapability, ExecutionProfile, ExecutionStatusResponse, Settings } from "@orc/types";
import { useCallback, useEffect, useState } from "react";
import { api } from "../api/client";
const input = "min-h-10 w-full min-w-0 rounded border border-neutral-700 bg-neutral-950 px-3 py-2 text-sm focus-visible:outline-2 focus-visible:outline-blue-400";
const button = "min-h-10 rounded border border-neutral-700 px-3 py-2 text-sm hover:bg-neutral-800 disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-blue-400";
export function ExecutionPanel({ settings, active, onChange, saved }: { settings: Settings; active: boolean; saved?: boolean; onChange: (patch: Pick<Settings, "models" | "executionProfiles">) => void }) {
  const [status, setStatus] = useState<ExecutionStatusResponse>();
  const [busy, setBusy] = useState<string>(); const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>(); const [notice, setNotice] = useState<string>();
  const [confirm, setConfirm] = useState<{ kind: "remove" | "stop"; id: string }>();
  const refresh = useCallback(async () => { setLoading(true); try { setStatus(await api<ExecutionStatusResponse>("executionStatus")); setError(undefined); } catch (e) { setError(e instanceof Error ? e.message : "Worker status is unavailable. Try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { if (active) void refresh(); }, [active, refresh, saved]);
  const profiles = settings.executionProfiles ?? []; const pools = (settings.accountPools ?? []).filter((pool) => pool.billing === "subscription");
  const patch = (id: string, change: Partial<ExecutionProfile>) => onChange({ models: settings.models, executionProfiles: profiles.map((profile) => profile.id === id ? { ...profile, ...change } : profile) });
  async function verify(id: string) {
    if (busy) return; setBusy(id); setError(undefined); setNotice(undefined);
    try { const result = await api<ExecutionCapability>("verifyExecutionProfile", { params: { profileId: id } }); await refresh(); if (result.state === "verified") setNotice(result.detail); else setError(result.detail); }
    catch (e) { setError(e instanceof Error ? e.message : "Verification failed. Your edits are preserved."); } finally { setBusy(undefined); }
  }
  async function stop(id: string) {
    if (busy) return; setBusy(id); setError(undefined); setNotice(undefined);
    try { setStatus(await api<ExecutionStatusResponse>("stopExecutionWorker", { params: { workerId: id } })); setConfirm(undefined); setNotice("Worker termination verified. Resolve any held account slot in Resources."); }
    catch (e) { setError(e instanceof Error ? e.message : "Termination could not be verified. Capacity remains protected."); } finally { setBusy(undefined); }
  }
  return <section aria-label="Agent execution" className="space-y-4 border-t border-neutral-800 pt-6">
    <h3 className="font-medium">Where agents run</h3>
    <p className="text-sm text-neutral-400">Host CLI is the default and has no app-enforced filesystem or network isolation. Docker profiles use a separate CLI login, an assigned workspace and a restricted network. Repository gates have their own sandbox setting.</p>
    <p className="text-xs text-neutral-500">The initial worker supports Codex 0.154.0 with a ChatGPT subscription. Use the setup guide to install the worker image and sign in. Save edits before verifying. Verification sends no model prompt; it does not prove model access or AWS readiness.</p>
    <div className="flex flex-wrap gap-2"><button className={button} disabled={loading || !!busy} onClick={() => void refresh()} aria-busy={loading}>{loading ? "Refreshing…" : "Refresh workers"}</button><button className={button} disabled={!pools.length} onClick={() => onChange({ models: settings.models, executionProfiles: [...profiles, { id: `worker-${crypto.randomUUID()}`, name: "Isolated Codex", kind: "docker", runner: "codex", image: "", accountVolume: "hoopedorc-account-codex", accountPoolId: pools[0]!.id, cpus: 2, memoryMiB: 1024, pidsLimit: 128 }] })}>Add Docker profile</button></div>
    <a href="https://github.com/IngeniousArtist/hoopedorc/blob/main/deploy/worker/README.md" target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center text-sm text-blue-300 underline focus-visible:outline-2 focus-visible:outline-blue-400">Worker setup guide ↗</a>
    {!pools.length && <p className="text-xs text-neutral-400">Add a subscription account pool above to configure an isolated worker.</p>}
    {loading && !status && <p role="status" className="text-sm">Loading execution status…</p>}
    {error && <p role="alert" className="break-words rounded border border-red-900 p-3 text-sm text-red-300">{error}</p>}
    {notice && <p role="status" className="text-sm text-green-300">{notice}</p>}
    {!profiles.length && <p className="text-sm text-neutral-400">No isolated profiles configured. Your existing host logins remain in use.</p>}
    {profiles.map((profile, index) => { const state = status?.profiles.find((item) => item.profileId === profile.id); const occupied = status?.workers.some((worker) => worker.profileId === profile.id && worker.state !== "stopped"); const prefix = `Worker ${index + 1}`;
      return <fieldset key={profile.id} className="min-w-0 space-y-3 rounded border border-neutral-800 p-4"><legend className="px-1 text-sm">{prefix}</legend><div className="grid gap-3 sm:grid-cols-2">
        <label className="text-xs text-neutral-400">Name<input className={input} aria-label={`${prefix} name`} value={profile.name} onChange={(e) => patch(profile.id, { name: e.target.value })} /></label>
        <label className="text-xs text-neutral-400">Subscription account<select className={input} aria-label={`${prefix} account`} value={profile.accountPoolId} onChange={(e) => patch(profile.id, { accountPoolId: e.target.value })}>{pools.map((pool) => <option key={pool.id} value={pool.id}>{pool.name}</option>)}</select></label>
        <label className="text-xs text-neutral-400 sm:col-span-2">Immutable image ID<input className={input} aria-label={`${prefix} image`} placeholder="sha256:…" value={profile.image} onChange={(e) => patch(profile.id, { image: e.target.value })} /></label>
        <label className="text-xs text-neutral-400 sm:col-span-2">CLI account volume<input className={input} aria-label={`${prefix} volume`} value={profile.accountVolume} onChange={(e) => patch(profile.id, { accountVolume: e.target.value })} /></label>
        <label className="text-xs text-neutral-400">CPU limit<input className={input} aria-label={`${prefix} CPUs`} type="number" min={0.25} max={16} step={0.25} value={profile.cpus} onChange={(e) => patch(profile.id, { cpus: Number(e.target.value) })} /></label>
        <label className="text-xs text-neutral-400">Memory in MiB<input className={input} aria-label={`${prefix} memory`} type="number" min={256} max={16384} value={profile.memoryMiB} onChange={(e) => patch(profile.id, { memoryMiB: Number(e.target.value) })} /></label>
        <label className="text-xs text-neutral-400">Process limit<input className={input} aria-label={`${prefix} processes`} type="number" min={32} max={1024} value={profile.pidsLimit} onChange={(e) => patch(profile.id, { pidsLimit: Number(e.target.value) })} /></label>
      </div><p className="break-words text-sm text-neutral-400">{state ? `${state.state === "verified" ? "Last check passed" : "Unavailable"}: ${state.detail}` : "Save settings, then verify the worker."}</p>
      {state?.checkedAt && <p className="text-xs text-neutral-500">Last checked {new Date(state.checkedAt).toLocaleString()}. Checked again before each model call.</p>}
      <div className="flex flex-wrap gap-2"><button className={button} disabled={!!busy || !state} aria-busy={busy === profile.id} onClick={() => void verify(profile.id)}>{busy === profile.id ? "Verifying…" : "Verify worker"}</button><button className={button} disabled={!!busy || occupied || !status} onClick={() => setConfirm({ kind: "remove", id: profile.id })}>Remove execution profile</button></div>
      {occupied && <p className="text-xs text-neutral-400">Stop or resolve this profile’s workers before removing it.</p>}
      {confirm?.kind === "remove" && confirm.id === profile.id && <div role="group" aria-label="Confirm execution profile removal" className="space-y-2 rounded border border-amber-800 p-3"><p className="text-sm">Remove this profile and return its models to host execution when you save?</p><div className="flex flex-wrap gap-2"><button className={button} onClick={() => { onChange({ executionProfiles: profiles.filter((item) => item.id !== profile.id), models: settings.models.map((model) => model.executionProfileId === profile.id ? { ...model, executionProfileId: undefined } : model) }); setConfirm(undefined); }}>Remove from draft</button><button className={button} onClick={() => setConfirm(undefined)}>Cancel</button></div></div>}
      </fieldset>; })}
    <h4 className="text-sm font-medium">Model execution</h4>{settings.models.map((model) => <label key={model.id} className="grid items-center gap-2 text-sm sm:grid-cols-2"><span className="break-words">{model.displayName}</span><select className={input} aria-label={`${model.displayName} execution`} value={model.executionProfileId ?? ""} onChange={(e) => onChange({ executionProfiles: profiles, models: settings.models.map((item) => item.id === model.id ? { ...item, executionProfileId: e.target.value || undefined } : item) })}><option value="">Host CLI · no isolation</option>{profiles.map((profile) => <option key={profile.id} value={profile.id} disabled={profile.runner !== model.runner || profile.accountPoolId !== model.accountPoolId}>{profile.name}{profile.runner !== model.runner || profile.accountPoolId !== model.accountPoolId ? " · requires matching Codex account" : ""}</option>)}</select></label>)}
    {status?.workers.filter((worker) => worker.state !== "stopped").map((worker) => <div key={worker.id} className="space-y-2 rounded border border-amber-900 p-3"><p className="break-words text-sm">{worker.profileId} · {worker.state} · {worker.taskId ?? "Verification / model check"}</p><p className="break-all text-xs text-neutral-500">{worker.workerName}</p>{confirm?.kind === "stop" && confirm.id === worker.id ? <div role="group" aria-label="Confirm worker termination" className="space-y-2"><p className="text-sm">Stop this worker and its network proxy? Uncommitted files remain in the workspace.</p><div className="flex flex-wrap gap-2"><button className={button} disabled={!!busy} aria-busy={busy === worker.id} onClick={() => void stop(worker.id)}>{busy === worker.id ? "Stopping…" : "Stop and verify"}</button><button className={button} disabled={!!busy} onClick={() => setConfirm(undefined)}>Cancel</button></div></div> : <><button className={button} disabled={!!busy || worker.state !== "unresolved"} onClick={() => setConfirm({ kind: "stop", id: worker.id })}>Stop owned worker</button>{worker.state !== "unresolved" && <p className="text-xs text-neutral-400">Stop the task from its project to cancel active work. Verification probes finish automatically.</p>}</>}</div>)}
  </section>;
}
